angular.module("YJA",[
	"ionic",
	"controllers.yja",
	"controllers.coachList",
	"controllers.message",
    "controllers.coachDetile",
    "controllers.imgList",
    "controllers.siteCoach",
    "controllers.getHospitalSite",
    "controllers.reloadr",
    "controllers.register",
    "controllers.loginTemp",
    "controllers.orderTemp",
    "controllers.person",
    "controllers.judgeMent",
    "controllers.orderMuch",
    "controllers.code",
    "controllers.fixName",
    "directives.coachList",
    "directives.getMap",
    "directives.todayOrder",
    "directives.orderMuch",
    "directives.belongFirst",
    "directives.belongSecond",
    "directives.orderList",
    "directives.belongThird",
    "directives.imgList",
    "directives.audioList",
    "directives.lMap",
	"services.common"
])
.config(function(
	$stateProvider,
	$locationProvider,
	$urlRouterProvider
){   
	$stateProvider
		.state('yja',{
			url:"/yja",
			templateUrl:"template/menu.html",
			controller:"yja"
		})
		.state('yja.coachList',{
            url:"/coachList",
            views:{
                'menuContent':{
                    templateUrl:"template/coachList.html",
                    controller:"coachList"
                }
            }
        })
        .state('yja.reload',{
            url:"/reload",
            views:{
                'menuContent':{
                    templateUrl:"template/reload.html",
                    controller:"reloadr"
                }
            }
        })
        .state('yja.coachDetile',{
            url:"/coachDetile/:coachId",
            views:{
                'menuContent':{
                    templateUrl:"template/coachDetile.html",
                    controller:"coachDetile"
                }
            }
        })
        .state('yja.message',{
            url:'/message',
            views:{
                'menuContent':{
                    templateUrl:'template/message.html',
                    controller:'message'
                }
            }
        })
        .state('yja.getHospitalSite',{
            url:'/getHospitalSite',
            views:{
                'menuContent':{
                    templateUrl:'template/getHospitalSite.html',
                    controller:'getHospitalSite'
                }
            }
        })
        ///yja/siteCoach/
        .state('yja.siteCoach',{
            url:'/siteCoach/:siteId',
            views:{
                'menuContent':{
                    templateUrl:'template/siteCoach.html',
                    controller:'siteCoach'
                }
            }
        })
        .state('yja.imgList',{
            url:'/imgList/:coachId',
            views:{
                'menuContent':{
                    templateUrl:'template/imgList.html',
                    controller:'imgList'
                }
            }
        })
        .state('yja.register',{
            url:'/register',
            views:{
                'menuContent':{
                    templateUrl:'template/register.html',
                    controller:'register'
                }
            }
        })
         .state('yja.login',{
            url:'/login',
            views:{
                'menuContent':{
                    templateUrl:'template/login.html',
                    controller:'loginTemp'
                }
            }
        })
        .state('yja.order',{
            url:'/order',
            views:{
                'menuContent':{
                    templateUrl:'template/orderTemp.html',
                    controller:'orderTemp'
                }
            }
        })
        .state('yja.person',{
            url:'/person',
            views:{
                'menuContent':{
                    templateUrl:'template/person.html',
                    controller:'person'
                }
            }
        })
        .state('yja.fixName',{
            url:'/fixName',
            views:{
                'menuContent':{
                    templateUrl:'template/fixName.html',
                    controller:'fixName'
                }
            }
        })
        .state('yja.code',{
            url:'/code',
            views:{
                'menuContent':{
                    templateUrl:'template/code.html',
                    controller:'code'
                }
            }
        })
        .state('yja.judgeMent',{
            url:'/judgeMent',
            views:{
                'menuContent':{
                    templateUrl:'template/judgeMent.html',
                    controller:'judgeMent'
                }
            }
        })
        .state('yja.orderMuch',{
            url:'/orderMuch',
            views:{
                'menuContent':{
                    templateUrl:'template/orderMuch.html',
                    controller:'orderMuch'
                }
            }
        })
		// $urlRouterProvider.otherwise("/yja/homePage");
		$locationProvider.html5Mode(true);
}) 
