angular.module("YJA",[
	"ionic",
	"controllers.yja",
	"controllers.classTable",
	"controllers.myself",
	"controllers.message",
    "controllers.login",
    // "directives.calEndar",
	"services.common"
])
.config(function(
	$stateProvider,
	$locationProvider,
	$urlRouterProvider
){   
	$stateProvider
		.state('yja',{
			url:"/yja",
			templateUrl:"template/menu.html",
			controller:"yja"
		})
        .state('login',{
            url:"/login",
            templateUrl:"login.html",
            controller:"login"
        })
		.state('yja.classTable',{
            url:"/classTable",
            views:{
                'menuContent':{
                    templateUrl:"template/classTable.html",
                    controller:"classTable"
                }
            }
        })
        .state('yja.message',{
            url:'/message',
            views:{
                'menuContent':{
                    templateUrl:'template/message.html',
                    controller:'message'
                }
            }
        })
        .state('yja.myself',{
            url:'/myself',
            views:{
                'menuContent':{
                    templateUrl:'template/myself.html',
                    controller:'myself'
                }
            }
        })
		$urlRouterProvider.otherwise("/login");
		$locationProvider.html5Mode(true);
}) 
